fragment postFields on Post {
    id
    title
} 

fragment authorFields on Author {
    name
    posts {
        ...postFields
    }
}

query getAuthor($id: Int!) {
    author(id: $id) {
        ...authorFields
    }
}

query getPosts {
    posts {
        ...postFields
    }
}
